### ISSUE TITLE
Rejecting Bluez.Agent.RequestConfirmation?

### ISSUE THREAD

**Issue by ARitz-Cracker** [WaeCo/node-bluez#12]
Hey, so, I'm just trying to build a UI on top of this thing, and I want to do the "if pins displayed on device" match kind of paring. I'm pretty sure my custom agent must implement `RequestConfirmation` to do this. However, let's say I want to cancel the connection. i.e. press "no" on the "Do these numbers match?" prompt. How do I tell bluetoothd this via this library? The bluez docs say:
```
Possible errors: org.bluez.Error.Rejected
                        org.bluez.Error.Canceled
```

Should I just callback with any Error or do I have to callback with that DBus object?

**Comment by WaeCo** [comment]
You need to call the callback with an DBus.Error Object.

```
const DBus = require('dbus');
callback(new DBus.Error('org.bluez.Error.Rejected', 'Rejected Message'));
```

**Comment by ARitz-Cracker** [comment]
Great, thanks!

Also, when I callback with an empty response, "Failed to encode reply value" gets sent to stdout. Since the reply is supposed to be empty anyway, nothing bad happens and everything still works. I guess this is node-dbus' problem?

**Comment by WaeCo** [comment]
Yes, I already opened an issue for that a while ago. https://github.com/Shouqun/node-dbus/issues/195
