### ISSUE TITLE
Adapter.GetDiscoveryFilters throws an error

### ISSUE THREAD

**Issue by Hypfer** [WaeCo/node-bluez#18]
https://github.com/WaeCo/node-bluez/blob/master/lib/Adapter.js#L185

`UnhandledPromiseRejectionWarning: TypeError: this._interface.GetDiscoveryFilters is not a function`

BlueZ Version 5.43-2+deb9u1

**Comment by WaeCo** [comment]
You bluez version does not support this function.
I think it got introduced in 5.48
