### ISSUE TITLE
Bluetooth Socket Crash

### ISSUE THREAD

**Issue by Vishal8523** [WaeCo/node-bluez#25]
When the bluetooth device connection is abruptly removed while the characteristics/data are being read, there is a crash in the bluetooth socket as shown below.

```
 ServicesResolved: false, Connected: false }
events.js:174
      throw er; // Unhandled 'error' event
      ^

SystemError: getaddrinfo error
    at BluetoothSocket.onRead (/home/ble/node_modules/bluetooth-socket/index.js:44:25)
Emitted 'error' event at:
    at process.nextTick (/home/ble/node_modules/bluetooth-socket/index.js:50:41)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
Appreciate your help

**Comment by WaeCo** [comment]
This is probably due to you disconnecting from the bus (ending the program) without closing an open socket.
You are supposed to close any opened BluetoothSocket socket instances with the .end() method before closing you dbus session.

**Comment by Vishal8523** [comment]
Thanks @WaeCo for the suggestion. It works.
