### ISSUE TITLE
BLE device no more discoverable after pairing DBUS error

### ISSUE THREAD

**Issue by Vishal8523** [WaeCo/node-bluez#31]
While pairing to a BLE device with the PIN, the below DBUS error is thrown:

`DBusError: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`

After this error, the device is no more discoverable until the system is rebooted.
Where as the BLE device is discoverable in other applications like nRF connect.

BlueZ version: 5.54

Appreciate your help in this regards.

**Comment by WaeCo** [comment]
This means that the pairing run in a timeout, this is not an issue with this library
