### ISSUE TITLE
Stream music from mobile phone to Beaglebone Black(BBB)

### ISSUE THREAD

**Issue by hoahiepnguyen** [WaeCo/node-bluez#5]
I try to enable bluetooth on my BBB by nodejs. My code is below:

> bluetooth.init().then(async() => {
    // listen on first bluetooth adapter
    const adapter = await bluetooth.getAdapter('hci0');
    await adapter.Powered('on');
    await adapter.Discoverable('on')
    console.log("Powered and Discoverable on")
    await bluetooth.registerDefaultAgent()
    console.log('Agent registered')
})

 My phone found BBB device. But, It can not connect to BBB. Please to help me resolve this problem?

**Comment by WaeCo** [comment]
Closed old issue
