### ISSUE TITLE
Pereipheral Example

### ISSUE THREAD

**Issue by Vzor-** [WaeCo/node-bluez#7]
It is taking me a while to set up a peripheral mock-up using this module. It would help greatly if there was a basic example. Edit: On closer examination I see that the requisite classes for advertisement aren't implemented.

**Comment by woodencatty** [comment]
you can use this example in "bleno"

https://github.com/noble/bleno/tree/master/examples/battery-service

**Comment by yannickadam** [comment]
Hi @WaeCo ,
Are you planning to implement Gatt Server functionality after migrating to dbus-next (declare services, characteristics, descriptors and start advertisement)?
Or do you think this should be handled in a separate library like noble/bleno?

**Comment by WaeCo** [comment]
Bluez does support this so I think this functionality would fit into this library.
Can you open an new issue for this.
Also checkout dbus-next branch to think about possible implementations.

**Comment by WaeCo** [comment]
See #19
