### ISSUE TITLE
how can i updated-scanning devices in Raspberry Pi 3?

### ISSUE THREAD

**Issue by woodencatty** [WaeCo/node-bluez#8]
Hi, i have some problem on my project.
when i start scan using StartDiscovery(); first time, it's fine.
but after that, remained devices(discovered when i scanned first time) are shown. and it's not updated.
how can i fix it?

i tried : 
 - using bluetooth adapter.RemoveDevice(device); before scanning
    var adapter = await bluetooth.getAdapter('hci0');
    await adapter.RemoveDevice(remove); // it pulls error, String can't be accepted?

**Comment by Sylvanik** [comment]
Did you find your answer?

**Comment by woodencatty** [comment]
no, i can't solve this issue. it was problem of bluez.

when bluez scan devices, it store information of scanned devices(dunno where it is).

so if i want update list, i have to clear that or wait for it(it takes 1-3mins. maybe)

so, i use another method(Wi-Fi connect) to do my job.

**Comment by Vishal8523** [comment]
@woodencatty : What is the fix for this issue ?
