### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by atrovato** [WaeCo/node-bluez#9]
Hello,
I tried to get "Service" object and its Characteristics, but the Device.getServices(uuid) always returns "undefined", the device services array is never filled.
(same for Service -> Characteristics).

Do you plan to finalize the implementation ?

**Comment by readeral** [comment]
I'm also curious about this. There's no function to actually populate the services object.

**Comment by WaeCo** [comment]
API was improved in v0.4.0
